import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import {BrowserRouter} from "react-router-dom";
import {Provider} from "react-redux";
import store from "./store/store";


ReactDOM.render(
  <React.StrictMode>
          <BrowserRouter>
              <Provider store={store}>
          <App />
              </Provider>
          </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);


reportWebVitals();


const film = [
    {"adult":false,"backdrop_path":"/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg","belongs_to_collection":null,"budget":200000000,"genres":[{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":53,"name":"Thriller"},{"id":878,"name":"Science Fiction"}],"homepage":"https://www.marvel.com/movies/black-widow","id":497698,"imdb_id":"tt3480822","original_language":"en","original_title":"Black Widow","overview":"Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.","popularity":8127.332,"poster_path":"/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg","production_companies":[{"id":420,"logo_path":"/hUzeosd33nzE5MCNsZxCGEKTXaQ.png","name":"Marvel Studios","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-07-07","revenue":251401120,"runtime":134,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"},{"english_name":"Russian","iso_639_1":"ru","name":"Pусский"}],"status":"Released","tagline":"She's Done Running From Her Past.","title":"Black Widow","video":false,"vote_average":8.0,"vote_count":2968},
    {"adult":false,"backdrop_path":"/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg","belongs_to_collection":{"id":848922,"name":"The Tomorrow War Collection","poster_path":null,"backdrop_path":null},"budget":0,"genres":[{"id":28,"name":"Action"},{"id":878,"name":"Science Fiction"}],"homepage":"https://www.amazon.com/dp/B093CQZ2SM","id":588228,"imdb_id":"tt9777666","original_language":"en","original_title":"The Tomorrow War","overview":"The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.","popularity":3969.898,"poster_path":"/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg","production_companies":[{"id":82819,"logo_path":"/5Z8WWr0Lf1tInVWwJsxPP0uMz9a.png","name":"Skydance Media","origin_country":"US"},{"id":423,"logo_path":"/uvA6e2O31qaonsbYd8tjvgqmNXh.png","name":"Phantom Four","origin_country":"US"},{"id":125000,"logo_path":null,"name":"Lit Entertainment Group","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-06-30","revenue":0,"runtime":138,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"The fight for tomorrow begins today.","title":"The Tomorrow War","video":false,"vote_average":8.3,"vote_count":2685},
    {"adult":false,"backdrop_path":"/8s4h9friP6Ci3adRGahHARVd76E.jpg","belongs_to_collection":{"id":722961,"name":"Space Jam Collection","poster_path":"/t6nnBWjHwPL9MXJ0kpjYEXeddxl.jpg","backdrop_path":"/x0qhpQ0GwBEjAdb7hPchQDevBvQ.jpg"},"budget":161900000,"genres":[{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":10751,"name":"Family"},{"id":878,"name":"Science Fiction"}],"homepage":"https://www.spacejam.com","id":379686,"imdb_id":"tt3554046","original_language":"en","original_title":"Space Jam: A New Legacy","overview":"When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.","popularity":7908.03,"poster_path":"/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg","production_companies":[{"id":25120,"logo_path":"/lqUpBvDLQYG3QaKNpe2lxfpgh36.png","name":"Warner Animation Group","origin_country":"US"},{"id":81170,"logo_path":"/degJG2ecLMkHndE5mFuWS8lTLBa.png","name":"SpringHill Entertainment","origin_country":"US"},{"id":2785,"logo_path":"/l5zW8jjmQOCx2dFmvnmbYmqoBmL.png","name":"Warner Bros. Animation","origin_country":"US"},{"id":148495,"logo_path":null,"name":"Proximity Media","origin_country":"US"},{"id":174,"logo_path":"/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png","name":"Warner Bros. Pictures","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-07-08","revenue":53153362,"runtime":115,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"},{"english_name":"Spanish","iso_639_1":"es","name":"Español"},{"english_name":"Swedish","iso_639_1":"sv","name":"svenska"},{"english_name":"Thai","iso_639_1":"th","name":"ภาษาไทย"}],"status":"Released","tagline":"Welcome to the Jam!","title":"Space Jam: A New Legacy","video":false,"vote_average":7.9,"vote_count":946},
    {"adult":false,"backdrop_path":"/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg","belongs_to_collection":{"id":519457,"name":"The Boss Baby Collection","poster_path":"/uVJPQ8wGZvW4h9Z7xpqToOxsuzH.jpg","backdrop_path":"/n2opkcFxIGc0plZJs45CAH8IjiF.jpg"},"budget":82000000,"genres":[{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":12,"name":"Adventure"},{"id":10751,"name":"Family"}],"homepage":"https://www.dreamworks.com/movies/the-boss-baby-2","id":459151,"imdb_id":"tt6932874","original_language":"en","original_title":"The Boss Baby: Family Business","overview":"The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.","popularity":4531.876,"poster_path":"/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg","production_companies":[{"id":521,"logo_path":"/kP7t6RwGz2AvvTkvnI1uteEwHet.png","name":"DreamWorks Animation","origin_country":"US"},{"id":33,"logo_path":"/8lvHyhjr8oUKOOy2dKXoALWKdp0.png","name":"Universal Pictures","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-07-01","revenue":48984525,"runtime":107,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Playtime is over.","title":"The Boss Baby: Family Business","video":false,"vote_average":8.0,"vote_count":763},
    {"adult":false,"backdrop_path":"/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":10751,"name":"Family"},{"id":14,"name":"Fantasy"}],"homepage":"https://www.disneyplus.com/movies/luca/7K1HyQ6Hl16P","id":508943,"imdb_id":"tt12801262","original_language":"en","original_title":"Luca","overview":"Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.","popularity":3359.187,"poster_path":"/jTswp6KyDYKtvC52GbHagrZbGvD.jpg","production_companies":[{"id":3,"logo_path":"/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png","name":"Pixar","origin_country":"US"},{"id":2,"logo_path":"/wdrCwmRnLFJhEoH8GSfymY85KHT.png","name":"Walt Disney Pictures","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-06-17","revenue":11600000,"runtime":95,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"},{"english_name":"Italian","iso_639_1":"it","name":"Italiano"}],"status":"Released","tagline":"","title":"Luca","video":false,"vote_average":8.1,"vote_count":3037},
    {"adult":false,"backdrop_path":"/tehpKMsls621GT9WUQie2Ft6LmP.jpg","belongs_to_collection":{"id":256322,"name":"The Purge Collection","poster_path":"/kklRqw1Mp7xTnHm2ifmPNshGB4D.jpg","backdrop_path":"/zLx0VxpzJt3E0cb4GodV10Wp0Lt.jpg"},"budget":18000000,"genres":[{"id":12,"name":"Adventure"},{"id":53,"name":"Thriller"},{"id":28,"name":"Action"},{"id":27,"name":"Horror"},{"id":37,"name":"Western"}],"homepage":"https://www.theforeverpurge.com","id":602223,"imdb_id":"tt10327252","original_language":"en","original_title":"The Forever Purge","overview":"All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end as they chase a group of immigrants who they want to punish because of their harsh historical past.","popularity":5034.505,"poster_path":"/uHA5COgDzcxjpYSHHulrKVl6ByL.jpg","production_companies":[{"id":3172,"logo_path":"/kDedjRZwO8uyFhuHamomOhN6fzG.png","name":"Blumhouse Productions","origin_country":"US"},{"id":2481,"logo_path":"/nVEP2IHCDOBOldgDL4SSufitN9.png","name":"Platinum Dunes","origin_country":"US"},{"id":33,"logo_path":"/8lvHyhjr8oUKOOy2dKXoALWKdp0.png","name":"Universal Pictures","origin_country":"US"},{"id":10338,"logo_path":"/el2ap6lvjcEDdbyJoB3oKiYgXu9.png","name":"Perfect World Pictures","origin_country":"CN"},{"id":138783,"logo_path":"/dCzNhv0G1Gz4u5piPyJy6n3wYWU.png","name":"Man in A Tree","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-06-30","revenue":49273105,"runtime":103,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"},{"english_name":"Spanish","iso_639_1":"es","name":"Español"}],"status":"Released","tagline":"The rules are broken.","title":"The Forever Purge","video":false,"vote_average":7.7,"vote_count":308},
    {"adult":false,"backdrop_path":"/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":878,"name":"Science Fiction"},{"id":28,"name":"Action"},{"id":53,"name":"Thriller"}],"homepage":"https://www.paramountplus.com/movies/infinite/gkYk2Ju73QiIYX8TrooFblbsaUfPugRz/","id":581726,"imdb_id":"tt6654210","original_language":"en","original_title":"Infinite","overview":"Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.","popularity":2558.264,"poster_path":"/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg","production_companies":[{"id":435,"logo_path":"/AjzK0s2w1GtLfR4hqCjVSYi0Sr8.png","name":"Di Bonaventura Pictures","origin_country":"US"},{"id":4,"logo_path":"/fycMZt242LVjagMByZOLUGbCvv3.png","name":"Paramount","origin_country":"US"},{"id":8537,"logo_path":null,"name":"Closest to the Hole Productions","origin_country":"US"},{"id":114732,"logo_path":"/tNCbisMxO5mX2X2bOQxHHQZVYnT.png","name":"New Republic Pictures","origin_country":"US"},{"id":8151,"logo_path":null,"name":"Fuqua Films","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-06-10","revenue":0,"runtime":106,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"","title":"Infinite","video":false,"vote_average":7.3,"vote_count":521},
    {"adult":false,"backdrop_path":"/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg","belongs_to_collection":{"id":9485,"name":"The Fast and the Furious Collection","poster_path":"/zQdytnqfsWKJlqazqfMBL2L7aql.jpg","backdrop_path":"/gC9BUFiROWtaMsluGYziZ6lR4OJ.jpg"},"budget":200000000,"genres":[{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":80,"name":"Crime"},{"id":53,"name":"Thriller"}],"homepage":"https://www.thefastsaga.com","id":385128,"imdb_id":"tt5433138","original_language":"en","original_title":"F9","overview":"Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.","popularity":2090.727,"poster_path":"/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg","production_companies":[{"id":333,"logo_path":"/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png","name":"Original Film","origin_country":"US"},{"id":1225,"logo_path":"/rIxhJMR7oK8b2fMakmTfRLY2TZv.png","name":"One Race","origin_country":"US"},{"id":34530,"logo_path":null,"name":"Perfect Storm Entertainment","origin_country":"US"},{"id":154215,"logo_path":null,"name":"ZXY MOVIES","origin_country":""}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-05-19","revenue":592683450,"runtime":145,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Justice is coming.","title":"F9","video":false,"vote_average":7.5,"vote_count":648},
    {"adult":false,"backdrop_path":"/5HjzYTihkH7EvOWSE7KcsF6pBMM.jpg","belongs_to_collection":{"id":595693,"name":"Peter Rabbit Collection","poster_path":"/vE4t3ULX3dP6o7Y2Pnf9sReYTqu.jpg","backdrop_path":"/62W2l6HduDpiXyg4kRLYBGmV7SV.jpg"},"budget":45000000,"genres":[{"id":10751,"name":"Family"},{"id":35,"name":"Comedy"},{"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":14,"name":"Fantasy"}],"homepage":"https://www.peterrabbit-movie.com/","id":522478,"imdb_id":"tt8376234","original_language":"en","original_title":"Peter Rabbit 2: The Runaway","overview":"Bea, Thomas, and the rabbits have created a makeshift family, but despite his best efforts, Peter can’t seem to shake his mischievous reputation. Adventuring out of the garden, Peter finds himself in a world where his mischief is appreciated, but when his family risks everything to come looking for him, Peter must figure out what kind of bunny he wants to be.","popularity":2022.69,"poster_path":"/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg","production_companies":[{"id":5,"logo_path":"/71BqEFAF4V3qjjMPCpLuyJFB9A.png","name":"Columbia Pictures","origin_country":"US"},{"id":7291,"logo_path":"/eo8YnSO7wpUHVEprnMDOUcalhFD.png","name":"Olive Bridge Entertainment","origin_country":"US"},{"id":34,"logo_path":"/GagSvqWlyPdkFHMfQ3pNq6ix9P.png","name":"Sony Pictures","origin_country":"US"}],"production_countries":[{"iso_3166_1":"AU","name":"Australia"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-03-25","revenue":127316482,"runtime":93,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"The garden was just the beginning.","title":"Peter Rabbit 2: The Runaway","video":false,"vote_average":7.4,"vote_count":180},
    {"adult":false,"backdrop_path":"/70AV2Xx5FQYj20labp0EGdbjI6E.jpg","belongs_to_collection":null,"budget":40000000,"genres":[{"id":80,"name":"Crime"},{"id":28,"name":"Action"},{"id":53,"name":"Thriller"}],"homepage":"https://www.miramax.com/movie/wrath-of-man","id":637649,"imdb_id":"tt11083552","original_language":"en","original_title":"Wrath of Man","overview":"A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.","popularity":2944.569,"poster_path":"/M7SUK85sKjaStg4TKhlAVyGlz3.jpg","production_companies":[{"id":14,"logo_path":"/m6AHu84oZQxvq7n1rsvMNJIAsMu.png","name":"Miramax","origin_country":"US"},{"id":21,"logo_path":"/aOWKh4gkNrfFZ3Ep7n0ckPhoGb5.png","name":"Metro-Goldwyn-Mayer","origin_country":"US"},{"id":2900,"logo_path":null,"name":"Toff Guy Films","origin_country":"GB"},{"id":1632,"logo_path":"/cisLn1YAUuptXVBa0xjq7ST9cH0.png","name":"Lionsgate","origin_country":"US"},{"id":141391,"logo_path":null,"name":"CAA Media Finance","origin_country":"US"}],"production_countries":[{"iso_3166_1":"GB","name":"United Kingdom"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-04-22","revenue":100455327,"runtime":119,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"},{"english_name":"Russian","iso_639_1":"ru","name":"Pусский"}],"status":"Released","tagline":"A one man army.","title":"Wrath of Man","video":false,"vote_average":7.8,"vote_count":1449},
    {"adult":false,"backdrop_path":"/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg","belongs_to_collection":{"id":837007,"name":"Cruella Collection","poster_path":null,"backdrop_path":null},"budget":200000000,"genres":[{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"}],"homepage":"https://movies.disney.com/cruella","id":337404,"imdb_id":"tt3228774","original_language":"en","original_title":"Cruella","overview":"In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.","popularity":1717.047,"poster_path":"/rTh4K5uw9HypmpGslcKd4QfHl93.jpg","production_companies":[{"id":2,"logo_path":"/wdrCwmRnLFJhEoH8GSfymY85KHT.png","name":"Walt Disney Pictures","origin_country":"US"}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2021-05-26","revenue":217036776,"runtime":134,"spoken_languages":[{"english_name":"English","iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Hello Cruel World","title":"Cruella","video":false,"vote_average":8.4,"vote_count":4222}
]
