export const ROLE_CHANGE = 'ROLE_CHANGE'
export const USERNAME_CHANGE = 'USERNAME_CHANGE'
export const ADD_USER = 'ADD_USER'
export const SET_LOADING = 'SET_LOADING'
export const SET_FILMDATA = 'SET_FILMDATA'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const API_KEY = '687697daf00f72e0a7e20cf9f55a44ec'